POST http://localhost:3000/login
Content-Type: application/json

{
    "firstName": "Hashirama",
    "lastName": "Senju",
    "email": "shinobi@gmail.com",
    "password": "123456",
    "mobile": "0256733334"
}

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "productName": "glove remote",
    "category": "tech",
    "productDescription": "size 4 glove remote",
    "image": "https://i.postimg.cc/L4kqgQDS/GLOVE-REMOTE.jpg",
    "price": 10000,
    "createby": ""
}

###
GET http://localhost:3000/users