POST http://localhost:3000/login
Content-Type: application/json

{
    "firstName": "Hashirama",
    "lastName": "Senju",
    "email": "shinobi@gmail.com",
    "password": "123456",
    "mobile": "0256733334"
}

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "productName": "Wrist Mobile",
    "category": "tech",
    "productDescription": "mobile phone used like a watch",
    "image": "https://i.postimg.cc/d0ZgqGLG/future-of-mobile-phones-pic6-removebg-preview.png",
    "price": 69000,
    "createby": "Tony Stark"
}

###
GET http://localhost:3000/users